steps:
  - name: node:10.15.1
    entrypoint: npm
    args: ["install"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["run"]
  - name: "gcr.io/cloud-builders/gcloud"
    dir: "server"
    args: ["app", "deploy"]
timeout: "1600s"